---
- hosts: all
  roles:
    - docker
    - k8s-base
  post_tasks:
    - name: Add vagrant to docker group
      user:
        name: vagrant
        group: docker

- hosts: masters
  vars:
    kubectl_user: vagrant
  roles:
    - k8s-master
  post_tasks:
    - name: Get join command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: Set join command
      set_fact:
        join_command: "{{ join_command_raw.stdout_lines[0] }}"

- hosts: workers
  tasks:
    - name: Join clusters
      shell: "{{ hostvars['master1'].join_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt
