require '../vagrantmachineclass'

nodes = [
  VM.new(
    hostname: 'master1',
    cpus: '2',
    memory: '2048',
    groups: ['masters']
  ),
  VM.new(
    hostname: 'worker1',
    memory: '2048',
    groups: ['workers']
  ),
  VM.new(
    hostname: 'worker2',
    groups: ['workers']
  ),
]


Vagrant.configure("2") do |config|
  if Vagrant.has_plugin?("vagrant-vbguest")
    config.vbguest.auto_update = false
  end
  if Vagrant.has_plugin?("vagrant-hostmanager")
    config.hostmanager.enabled = true
    config.hostmanager.manage_host = true
  end
  nodes.each_with_index do |node, i|
    config.vm.define node.hostname do |node_config|
      node_config.vm.box = node.box
      node_config.vm.hostname = node.hostname
      node_config.vm.network :private_network, ip: "172.17.64.#{i + 100}"
      node_config.hostmanager.aliases = node.aliases
      node_config.vm.provider :virtualbox do |vbox|
        vbox.name = node.hostname
        vbox.memory = node.memory
        vbox.cpus = node.cpus
      end
    if i + 1 == nodes.length
      node_config.vm.provision "ansible" do |ansible|
        ansible.limit = "all"
        ansible.playbook = "provision.yml"
        ansible.groups = node.class.groups
      end
    end
    end
  end
end

# vi: set ft=ruby:
