---
- name: Install libvirt deps and tools
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - libvirt-bin
      - qemu-kvm
      - uvtool
      - virtinst
