---
- name: Include ttyd build deps
  apt:
    name: "{{ packages }}"
    state: present
    update_cache: yes
  vars:
    packages:
      - cmake
      - g++
      - pkg-config
      - git
      - vim-common
      - libwebsockets-dev
      - libjson-c-dev
      - libssl-dev

- name: Clone ttyd repo for custom builds if necessary
  git:
    repo: https://github.com/tsl0922/ttyd
    version: master
    dest: "/home/{{ username }}/ttyd-repo"
  become_user: "{{ username }}"

