---
- name: Add wireguard ppa
  apt_repository:
    repo: ppa:wireguard/wireguard

- name: Install wireguard
  apt:
    name: wireguard
    state: present
    update_cache: yes

- name: Generate wireguard public and private keys
  shell: wg genkey | tee privatekey | wg pubkey > publickey
  args:
    chdir: /etc/wireguard
    creates: /etc/wireguard/privatekey

- name: Add wireguard conf
  template:
    src: wg0.conf.j2
    dest: /etc/wireguard/wg0.conf
  vars:
    client_keys: "{{ lookup('file', 'publicKeys').splitlines() }}"

- name: Add private key to wg0.conf
  shell: sed -E -i "s@<.+>@$(cat privatekey)@" wg0.conf
  args:
    chdir: /etc/wireguard

- name: Create wireguard interface
  shell: wg-quick up wg0
  args:
    chdir: /etc/wireguard
